name: Actions

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and Push Docker Image
      run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "ernestlauwers" --password-stdin
          docker image build -t ernestlauwers/pe-frontend:latestFrontend .
          docker push ernestlauwers/pe-frontend:latestFrontend
    - name: Create Release  
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.CI_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE.txt
          *.jar
