name: Test, Docker, Release

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v1
    - name: Build and Push Docker Image
      run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "ernestlauwers" --password-stdin
          docker image build -t ernestlauwers/pe-besturingsystemen2:latest .
          docker push ernestlauwers/pe-besturingsystemen2:latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install project
      run: npm ci
    - name: Build the project
      run: npm run build --if-present
    - name: Run tests
      run: npm test
